#ifndef ADVANCED_SETTINGS_HLSL
#define ADVANCED_SETTINGS_HLSL

#define DIFFUSE_MODE_LAMBERT    0
#define DIFFUSE_MODE_BURLEY     1
#define DIFFUSE_MODE_ORENNAYAR  2
#define DIFFUSE_MODE_GOTANDA    3
#define DIFFUSE_MODE_CHAN       4

#define LIGHTEVAL_MODE_DIFFUSE  0
#define LIGHTEVAL_MODE_BRDF     1

#define LIGHTING_MODE_DIFFUSE    0
#define LIGHTING_MODE_PBR        1

#ifndef RIS_MAX_CANDIDATES
#define RIS_MAX_CANDIDATES (4)
#endif

#endif // ADVANCED_SETTINGS_HLSL