[Info]
; Defines version of this feature
Version = 1-0-0
Description = Ray traced global illumination for Skyrim using KickstartRT

[Settings]
; General settings
Enabled = true
Intensity = 1.0
Distance = 200.0
Saturation = 1.0
AdaptToScene = false
InteriorIntensityMultiplier = 1.2
ExteriorIntensityMultiplier = 0.8 