[Info]
; Defines version of this feature
Version = 1-0-0
Description = Ray tracing support for Skyrim using KickstartRT

[Settings]
; General settings
Enabled = false
EnableGI = true
EnableReflections = false

; GI Settings
GIIntensity = 1.0
GIDistance = 100.0
GISaturation = 1.0
GISampleCount = 1

; Reflection Settings
ReflectionIntensity = 1.0
ReflectionRoughness = 0.5
ReflectionDistance = 200.0
ReflectionSampleCount = 1

; Denoising
EnableDenoising = true
MaxDenoiserHistory = 8
DenoiserBlend = 0.1

; Debug
ShowRaytracedResults = false
