"""Reduce OPAC 4.0 optical data to Physical Sky's RGB aerosol tables."""

import argparse
import hashlib
from pathlib import Path
import re
import zipfile


HUMIDITIES = (0, 50, 70, 80, 90, 95, 98, 99)
WAVELENGTHS = (0.680, 0.550, 0.440)
MIXTURES = (
    (("inso", 0.15), ("waso", 2600.0)),
    (("waso", 1500.0), ("ssam", 20.0), ("sscm", 0.0032)),
    (("inso", 1.5), ("waso", 28000.0), ("soot", 130000.0)),
    (("waso", 2000.0), ("minn", 269.5), ("mian", 30.5), ("micn", 0.142)),
)
ARCHIVE_SHA256 = "561d95f60e7151861f0114f7e654b85fb763ed367263ba76255780fc735d110d"


def read_component(archive, component, humidity):
    if component not in ("waso", "ssam", "sscm"):
        humidity = 0
    text = archive.read(f"opac_40b/optdat/{component}{humidity:02d}").decode("ascii")
    rows = []
    for line in text.split("# volume phase function")[0].splitlines():
        values = line.lstrip("# ").split()
        if len(values) == 9 and re.fullmatch(r"\d\.\d+E[+-]\d+", values[0]):
            row = [float(value) for value in values]
            rows.append((row[0], row[2], row[3], row[2] * row[5]))
    if len(rows) != 61:
        raise ValueError(f"Unexpected optical table: {component}{humidity:02d}")
    return rows


def interpolate(rows, wavelength):
    for lower, upper in zip(rows, rows[1:]):
        if lower[0] <= wavelength <= upper[0]:
            t = (wavelength - lower[0]) / (upper[0] - lower[0])
            return [a * (1.0 - t) + b * t for a, b in zip(lower[1:], upper[1:])]
    raise ValueError(f"Wavelength outside table: {wavelength}")


def cpp_float(value):
    result = f"{value:.9g}"
    if "." not in result and "e" not in result:
        result += ".0"
    return result + "f"


def generate(archive):
    lines = [
        "// OPAC 4.0: https://doi.org/10.5281/zenodo.7275005",
        "// Generated by tools/generate-aerosol-data.py; see docs/physical-sky/aerosols.md.",
        "static constexpr float humidityLevels[] = { 0.f, 50.f, 70.f, 80.f, 90.f, 95.f, 98.f, 99.f };",
        "static const Sample samples[4][8] = {",
    ]
    for mixture in MIXTURES:
        lines.append("\t{")
        for humidity in HUMIDITIES:
            rgb = [[0.0, 0.0, 0.0] for _ in WAVELENGTHS]
            for component, concentration in mixture:
                rows = read_component(archive, component, humidity)
                for index, wavelength in enumerate(WAVELENGTHS):
                    for column, value in enumerate(interpolate(rows, wavelength)):
                        rgb[index][column] += value * concentration * 1000.0
            scatter = ", ".join(cpp_float(channel[0]) for channel in rgb)
            absorption = ", ".join(cpp_float(channel[1]) for channel in rgb)
            moment = cpp_float(rgb[1][2])
            lines.append(f"\t\t{{ {{ {scatter} }}, {{ {absorption} }}, {moment} }},")
        lines.append("\t},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path, help="opac_40b.zip from Zenodo record 7275005")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if hashlib.sha256(args.archive.read_bytes()).hexdigest() != ARCHIVE_SHA256:
        raise ValueError("The archive does not match the published OPAC 4.0 data")
    with zipfile.ZipFile(args.archive) as archive:
        generated = generate(archive)
    output = Path(__file__).resolve().parents[1] / "src/Features/PhysicalSky/AerosolData.inl"
    if args.check:
        if output.read_text(encoding="utf-8") != generated:
            raise SystemExit("AerosolData.inl is out of date")
        print("AerosolData.inl matches the OPAC source data")
    else:
        output.write_text(generated, encoding="utf-8", newline="\r\n")


if __name__ == "__main__":
    main()
